name: Static Build

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'cusquitonet/web'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/Setup-python@v5
        with:
          python-version: '3.12'

      - name: Run build script
        run: python ./remote_build.sh

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update static build
          commit_user_name: Cusquito79
          commit_user_mail: cusquitonet@hotmail.com
          commit_author: cusquito79
